#---:wq--------------------------------------------------------------------------
# Copyright (c) 2009, MediaTek Inc.
# All rights reserved.
#
# Unauthorized use, practice, perform, copy, distribution, reproduction,
# or disclosure of this information in whole or in part is prohibited.
#-----------------------------------------------------------------------------
# $RCSfile:  $
# $Revision:
# $Date:
# $Author:  $
# $CCRevision:  $
# $SWAuthor:  $
# $MD5HEX:  $
#
# Description:
#        A set of files describing the framebuffer interface and core types.
#---------------------------------------------------------------------------*/

all:
	ln -fs libQtCore.so.4.8.3     libQtCore.so
	ln -fs libQtCore.so.4.8.3     libQtCore.so.4
	ln -fs libQtCore.so.4.8.3     libQtCore.so.4.8
	ln -fs libQtGui.so.4.8.3      libQtGui.so
	ln -fs libQtGui.so.4.8.3      libQtGui.so.4
	ln -fs libQtGui.so.4.8.3      libQtGui.so.4.8
	ln -fs libQtNetwork.so.4.8.3  libQtNetwork.so
	ln -fs libQtNetwork.so.4.8.3  libQtNetwork.so.4
	ln -fs libQtNetwork.so.4.8.3  libQtNetwork.so.4.8
	ln -fs libQtSql.so.4.8.3  libQtSql.so
	ln -fs libQtSql.so.4.8.3  libQtSql.so.4
	ln -fs libQtSql.so.4.8.3  libQtSql.so.4.8
	ln -fs libQtTest.so.4.8.3      libQtTest.so
	ln -fs libQtTest.so.4.8.3      libQtTest.so.4
	ln -fs libQtTest.so.4.8.3      libQtTest.so.4.8
	ln -fs libQtXml.so.4.8.3      libQtXml.so
	ln -fs libQtXml.so.4.8.3      libQtXml.so.4
	ln -fs libQtXml.so.4.8.3      libQtXml.so.4.8
	ln -fs libQtScript.so.4.8.3   libQtScript.so
	ln -fs libQtScript.so.4.8.3   libQtScript.so.4
	ln -fs libQtScript.so.4.8.3   libQtScript.so.4.8
	ln -fs libQtDeclarative.so.4.8.3 libQtDeclarative.so
	ln -fs libQtDeclarative.so.4.8.3 libQtDeclarative.so.4
	ln -fs libQtDeclarative.so.4.8.3 libQtDeclarative.so.4.8
	ln -fs /basic/lib/DFHEI5-SONY.ttf  ./fonts/DFHEI5-SONY.ttf
	ln -fs /basic/lib/SSTDTV-Roman-2012_mod.ttf  ./fonts/SSTDTV-Roman-2012_mod.ttf
	ln -fs /basic/lib/BitsThaiBT_303655.ttf  ./fonts/BitsThaiBT_303655.ttf
	ln -fs /basic/lib/KohinoorAssamese-Demi.ttf  ./fonts/KohinoorAssamese-Demi.ttf
	ln -fs /basic/lib/KohinoorBengali-Demi.ttf  ./fonts/KohinoorBengali-Demi.ttf
	ln -fs /basic/lib/KohinoorGujarati-Demi.ttf  ./fonts/KohinoorGujarati-Demi.ttf
	ln -fs /basic/lib/KohinoorGurmukhi-Demi.ttf  ./fonts/KohinoorGurmukhi-Demi.ttf
	ln -fs /basic/lib/KohinoorGurmukhi-Demi.ttf  ./fonts/KohinoorGurmukhi-Demi.ttf
	ln -fs /basic/lib/KohinoorHindi-Demi.ttf  ./fonts/KohinoorHindi-Demi.ttf
	ln -fs /basic/lib/KohinoorKannada-Demi.ttf  ./fonts/KohinoorKannada-Demi.ttf
	ln -fs /basic/lib/KohinoorMalayalam-Demi.ttf  ./fonts/KohinoorMalayalam-Demi.ttf
	ln -fs /basic/lib/KohinoorMarathi-Demi.ttf  ./fonts/KohinoorMarathi-Demi.ttf
	ln -fs /basic/lib/KohinoorOdia-Demi.ttf  ./fonts/KohinoorOdia-Demi.ttf
	ln -fs /basic/lib/KohinoorTamil-Demi.ttf  ./fonts/KohinoorTamil-Demi.ttf
	ln -fs /basic/lib/KohinoorTelugu-Demi.ttf  ./fonts/KohinoorTelugu-Demi.ttf
	ln -fs /basic/lib/mtk_special_add_on.ttf  ./fonts/mtk_special_add_on.ttf
	ln -fs /basic/lib/Sakkal_Majalla_Unicode-Md.ttf  ./fonts/Sakkal_Majalla_Unicode-Md.ttf
	ln -fs /basic/lib/SSTDTV-Light_20140904.ttf  ./fonts/SSTDTV-Light_20140904.ttf
	ln -fs /basic/lib/SSTDTV-Light-2012.ttf  ./fonts/SSTDTV-Light-2012.ttf
	ln -fs /basic/lib/SSTDTV-Roman_20140904.ttf  ./fonts/SSTDTV-Roman_20140904.ttf
	ln -fs /basic/lib/SSTDTV-Roman-2012_mod.ttf  ./fonts/SSTDTV-Roman-2012_mod.ttf

clean:
	rm -rf libQtCore.so
	rm -rf libQtCore.so.4
	rm -rf libQtCore.so.4.8
	rm -rf libQtDeclarative.so
	rm -rf libQtDeclarative.so.4
	rm -rf libQtDeclarative.so.4.8
	rm -rf libQtGui.so
	rm -rf libQtGui.so.4
	rm -rf libQtGui.so.4.8
	rm -rf libQtNetwork.so
	rm -rf libQtNetwork.so.4
	rm -rf libQtNetwork.so.4.8
	rm -rf libQtScript.so
	rm -rf libQtScript.so.4
	rm -rf libQtScript.so.4.8
	rm -rf libQtSql.so
	rm -rf libQtSql.so.4
	rm -rf libQtSql.so.4.8
	rm -rf libQtTest.so
	rm -rf libQtTest.so.4
	rm -rf libQtTest.so.4.8
	rm -rf libQtXml.so
	rm -rf libQtXml.so.4
	rm -rf libQtXml.so.4.8
	rm -rf libQtDeclarative.so
	rm -rf libQtDeclarative.so.4
	rm -rf libQtDeclarative.so.4.8
	rm -rf ./fonts/SSTDTV-Roman-2012_mod.ttf
	rm -rf ./fonts/DFHEI5-SONY.ttf
	rm -rf ./fonts/BitsThaiBT_303655.ttf
	rm -rf ./fonts/KohinoorBengali-Demi.ttf
	rm -rf ./fonts/KohinoorAssamese-Demi.ttf
	rm -rf ./fonts/KohinoorGujarati-Demi.ttf
	rm -rf ./fonts/KohinoorGurmukhi-Demi.ttf
	rm -rf ./fonts/KohinoorHindi-Demi.ttf
	rm -rf ./fonts/KohinoorKannada-Demi.ttf
	rm -rf ./fonts/KohinoorMalayalam-Demi.ttf
	rm -rf ./fonts/KohinoorMarathi-Demi.ttf
	rm -rf ./fonts/KohinoorOdia-Demi.ttf
	rm -rf ./fonts/KohinoorTamil-Demi.ttf
	rm -rf ./fonts/KohinoorTelugu-Demi.ttf
	rm -rf ./fonts/mtk_special_add_on.ttf
	rm -rf ./fonts/Sakkal_Majalla_Unicode-Md.ttf
	rm -rf ./fonts/SSTDTV-Light_20140904.ttf
	rm -rf ./fonts/SSTDTV-Light-2012.ttf
	rm -rf ./fonts/SSTDTV-Roman_20140904.ttf
	rm -rf ./fonts/SSTDTV-Roman-2012_mod.ttf

